version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: echo "npm install"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: echo "Testing Code"
      - run: npm install
      - run: npm run test
  hithere:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: echo "Hellow"
workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
        requires:
          - hithere
